chore: add general PR template
eclipse-tractusx/.github pull request #5
Opened 2023-04-28 08:43 UTC by SebastianBezold

## Description 

This PR introduces an org wide pull request template with basic a basic structure, that contributors can follow.
Also included is a list of checks, that contributors should complete, before asking committers for review. 
A list with links to further reading and project guidelines is included at the end.

fixes #4

2023-04-28 09:31 UTC, FaGru3n requested changes
Looks good for the Commiter Round... just small addition from myside

2023-04-28 09:31 UTC, FaGru3n commented on .github/pull_request_template.md
> +Fixes # (issue)
i would add `(https://github.com/eclipse-tractusx/<product-repo>/issues/<number-of-the-issue>)`
to make it clear to open issues for ETX

2023-04-28 09:31 UTC, FaGru3n commented on .github/pull_request_template.md
> +
we could also add here the committer guidelines from Eclipse (https://www.eclipse.org/legal/committerguidelines.php)

2023-04-28 09:34 UTC, SebastianBezold commented on .github/pull_request_template.md
> +Fixes # (issue)
Hmm. If you open a PR and add an issue via '#', you are anyways tied to issues in the repo you open the PR on

2023-04-28 11:25 UTC, Siegfriedk reviewed
Can we also add a hint on how to contribute to this template?

2023-04-28 18:55 UTC, Essenbreis commented
Is there a possibility to add security checks in this template? We could elaborate together in a meeting how this could look like @the-tatanka - Was hättest Du für Ideen?

2023-05-02 07:49 UTC, Siegfriedk commented
> 

@Essenbreis we can! We should! :) unfortunate our security meeting was skipped due to a few meetings but it will happen this week. So perhaps a topic for that.

2023-05-16 21:42 UTC, the-tatanka commented
> Is there a possibility to add security checks in this template? We could elaborate together in a meeting how this could look like @the-tatanka - What would be your ideas?

if we go full open source, that's a good option.

2023-05-22 09:11 UTC, FaGru3n approved these changes
LGTM 👍🏼

2023-05-22 09:11 UTC, FaGru3n commented on .github/pull_request_template.md
> +Fixes # (issue)
legit

2023-06-15 08:36 UTC, almadigabor commented
What's the status here? Can we merge and close? Adding security checks can be discussed in a separate new issue.

2023-06-15 08:45 UTC, Essenbreis commented
Hi Gabor, I agree security checks can be discussed in a separate new issue, We first have to align internally our security strategy. You can merge and close.

2023-06-15 09:19 UTC, merged

2023-06-15 09:21 UTC, almadigabor commented
Great, thanks for the heads up @Essenbreis! :) As soon as you're aligned internally, feel free to open an issue [on our board](https://github.com/eclipse-tractusx/sig-infra/issues/new/choose),